In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/manish0222/TE_SEM_6/main/ds_lab/ASGN1/melb_data_1.csv")
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [3]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [5]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [6]:
df.tail(10)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
13570,Wantirna South,34 Fewster Dr,3,h,970000.0,S,Barry,26/08/2017,14.7,3152.0,...,2.0,2.0,674.0,NaN,NaN,NaN,-37.88360,145.22805,Eastern Metropolitan,7082.0
13571,Wantirna South,15 Mara Cl,4,h,1330000.0,S,Barry,26/08/2017,14.7,3152.0,...,2.0,2.0,717.0,191.0,1980.0,NaN,-37.86887,145.22116,Eastern Metropolitan,7082.0
13572,Watsonia,76 Kenmare St,2,h,650000.0,PI,Morrison,26/08/2017,14.5,3087.0,...,1.0,1.0,210.0,79.0,2006.0,NaN,-37.70657,145.07878,Northern Metropolitan,2329.0
13573,Werribee,5 Nuragi Ct,4,h,635000.0,S,hockingstuart,26/08/2017,14.7,3030.0,...,2.0,1.0,662.0,172.0,1980.0,NaN,-37.89327,144.64789,Western Metropolitan,16166.0
13574,Westmeadows,9 Black St,3,h,582000.0,S,Red,26/08/2017,16.5,3049.0,...,2.0,2.0,256.0,NaN,NaN,NaN,-37.67917,144.89390,Northern Metropolitan,2474.0
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [7]:
df.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [8]:
df.shape

(13580, 21)

In [9]:
col_to_fill = ["Car", "BuildingArea", "YearBuilt"]
df[col_to_fill]= df[col_to_fill].fillna(df[col_to_fill].mean())
df.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [10]:
df=df.ffill()
df=df.bfill()
df.isna().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

In [11]:
df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [12]:
df['Rooms'].unique()

array([ 2,  3,  4,  1,  6,  5,  8,  7, 10], dtype=int64)

In [13]:
df["Landsize"]=np.sqrt(df["Landsize"])
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,14.212670,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,12.489996,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,11.575837,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,9.695360,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,10.954451,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,25.534291,151.96765,1981.000000,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,18.248288,133.00000,1995.000000,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,20.880613,151.96765,1997.000000,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,29.427878,157.00000,1920.000000,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,19.026298,112.00000,1920.000000,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0

In [14]:
rr=np.array(df["Rooms"])
l=len(rr)
s=sum(rr)
print(f"Mean: {s/l}")

Mean: 2.9379970544919

In [15]:
df["Rooms"].replace([1,2,3,4,5,6,7,8,9,10],
                    ["1BHK","2BHK","3BHK","4BHK","5BHK","6BHK","7BHK","8BHK","9BHK","10BHK"],inplace=True)
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,14.212670,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,12.489996,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,11.575837,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,9.695360,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,10.954451,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,25.534291,151.96765,1981.000000,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,18.248288,133.00000,1995.000000,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,20.880613,151.96765,1997.000000,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,29.427878,157.00000,1920.000000,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,19.026298,112.00000,1920.000000,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0

In [16]:
!pip install category_encoders
import category_encoders as ce

Requirement already satisfied: category_encoders in c:\users\aditya kadu\anaconda3\lib\site-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in c:\users\aditya kadu\anaconda3\lib\site-packages (from category_encoders) (1.24.3)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\aditya kadu\anaconda3\lib\site-packages (from category_encoders) (1.3.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\aditya kadu\anaconda3\lib\site-packages (from category_encoders) (1.10.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\aditya kadu\anaconda3\lib\site-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in c:\users\aditya kadu\anaconda3\lib\site-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\aditya kadu\anaconda3\lib\site-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\aditya kadu\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\aditya kadu\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2022.7)
Requirement already satisfied: six in c:\users\aditya kadu\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\aditya kadu\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\aditya kadu\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\aditya kadu\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (23.0)

In [17]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,14.212670,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,12.489996,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,11.575837,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,9.695360,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,10.954451,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,25.534291,151.96765,1981.000000,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,18.248288,133.00000,1995.000000,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,20.880613,151.96765,1997.000000,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,29.427878,157.00000,1920.000000,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,19.026298,112.00000,1920.000000,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0

In [18]:
#1. Label Encoding
label_encoder_rooms = LabelEncoder()
df["Rooms_encoded"]=label_encoder_rooms.fit_transform(df["Rooms"])
newarr = ["Rooms_encoded", "Rooms"]
df[newarr]

       Rooms_encoded Rooms
0                  2  2BHK
1                  2  2BHK
2                  3  3BHK
3                  3  3BHK
4                  4  4BHK
...              ...   ...
13575              4  4BHK
13576              3  3BHK
13577              3  3BHK
13578              4  4BHK
13579              4  4BHK

[13580 rows x 2 columns]

In [19]:
# 2. One-hot Encoding
df_one_hot = pd.get_dummies(df, columns = ["Rooms"], prefix= ["Rooms"])
df_one_hot

,Suburb,Address,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,...,Rooms_encoded,Rooms_10BHK,Rooms_1BHK,Rooms_2BHK,Rooms_3BHK,Rooms_4BHK,Rooms_5BHK,Rooms_6BHK,Rooms_7BHK,Rooms_8BHK
0,Abbotsford,85 Turner St,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,...,2,0,0,1,0,0,0,0,0,0
1,Abbotsford,25 Bloomburg St,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,...,2,0,0,1,0,0,0,0,0,0
2,Abbotsford,5 Charles St,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,...,3,0,0,0,1,0,0,0,0,0
3,Abbotsford,40 Federation La,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,...,3,0,0,0,1,0,0,0,0,0
4,Abbotsford,55a Park St,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,...,4,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,4.0,...,4,0,0,0,0,1,0,0,0,0
13576,Williamstown,77 Merrett Dr,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,3.0,...,3,0,0,0,1,0,0,0,0,0
13577,Williamstown,83 Power St,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,3.0,...,3,0,0,0,1,0,0,0,0,0
13578,Williamstown,96 Verdon St,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,4.0,...,4,0,0,0,0,1,0,0,0,0
13579,Yarraville,6 Agnes St,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,4.0,...,4,0,0,0,0,1,0,0,0,0

In [20]:
# 3. Ordinal Encoding
ordinal_mapping_rooms = {'1BHK': 1, '2BHK': 2, '3BHK': 3, '4BHK': 4, '5BHK': 5, '6BHK': 6, '7BHK': 7, '8BHK': 8, '10BHK': 10}
df['Rooms_OrdinalEncoded'] = df['Rooms'].map(ordinal_mapping_rooms)
newarr.append("Rooms_OrdinalEncoded")
df[newarr]

       Rooms_encoded Rooms  Rooms_OrdinalEncoded
0                  2  2BHK                     2
1                  2  2BHK                     2
2                  3  3BHK                     3
3                  3  3BHK                     3
4                  4  4BHK                     4
...              ...   ...                   ...
13575              4  4BHK                     4
13576              3  3BHK                     3
13577              3  3BHK                     3
13578              4  4BHK                     4
13579              4  4BHK                     4

[13580 rows x 3 columns]

In [21]:
# 4. Binary Encoding
binary_encoder = ce.BinaryEncoder(cols = ["Rooms"])
df_binary_encode = binary_encoder.fit_transform(df)
df_binary_encode

,Suburb,Address,Rooms_0,Rooms_1,Rooms_2,Rooms_3,Type,Price,Method,SellerG,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Rooms_encoded,Rooms_OrdinalEncoded
0,Abbotsford,85 Turner St,0,0,0,1,h,1480000.0,S,Biggin,...,14.212670,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,2,2
1,Abbotsford,25 Bloomburg St,0,0,0,1,h,1035000.0,S,Biggin,...,12.489996,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,2,2
2,Abbotsford,5 Charles St,0,0,1,0,h,1465000.0,SP,Biggin,...,11.575837,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,3,3
3,Abbotsford,40 Federation La,0,0,1,0,h,850000.0,PI,Biggin,...,9.695360,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,3,3
4,Abbotsford,55a Park St,0,0,1,1,h,1600000.0,VB,Nelson,...,10.954451,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,0,0,1,1,h,1245000.0,S,Barry,...,25.534291,151.96765,1981.000000,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,4,4
13576,Williamstown,77 Merrett Dr,0,0,1,0,h,1031000.0,SP,Williams,...,18.248288,133.00000,1995.000000,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0,3,3
13577,Williamstown,83 Power St,0,0,1,0,h,1170000.0,S,Raine,...,20.880613,151.96765,1997.000000,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0,3,3
13578,Williamstown,96 Verdon St,0,0,1,1,h,2500000.0,PI,Sweeney,...,29.427878,157.00000,1920.000000,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0,4,4
13579,Yarraville,6 Agnes St,0,0,1,1,h,1285000.0,SP,Village,...,19.026298,112.00000,1920.000000,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0,4,4

In [22]:
df["distancecopy"]=df["Distance"]
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Rooms_encoded,Rooms_OrdinalEncoded,distancecopy
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,2,2,2.5
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,2,2,2.5
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,3,3,2.5
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,3,3,2.5
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,4,4,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,151.96765,1981.000000,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,4,4,16.7
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,133.00000,1995.000000,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0,3,3,6.8
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,151.96765,1997.000000,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0,3,3,6.8
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,157.00000,1920.000000,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0,4,4,6.8
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,112.00000,1920.000000,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0,4,4,6.3

In [23]:
# Normalisation
df["distancecopy"]=(df["distancecopy"]-min(df["distancecopy"]))/(max(df["distancecopy"])-df["distancecopy"])
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Rooms_encoded,Rooms_OrdinalEncoded,distancecopy
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,2,2,0.054825
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,2,2,0.054825
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,3,3,0.054825
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,3,3,0.054825
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,4,4,0.054825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,151.96765,1981.000000,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,4,4,0.531847
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,133.00000,1995.000000,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0,3,3,0.164649
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,151.96765,1997.000000,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0,3,3,0.164649
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,157.00000,1920.000000,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0,4,4,0.164649
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,112.00000,1920.000000,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0,4,4,0.150718

In [24]:
df.drop(['distancecopy'], axis=1, inplace=True)

In [25]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Rooms_encoded,Rooms_OrdinalEncoded
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,14.212670,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,2,2
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,12.489996,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,2,2
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,11.575837,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,3,3
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,9.695360,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,3,3
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,10.954451,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,25.534291,151.96765,1981.000000,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,4,4
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,18.248288,133.00000,1995.000000,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0,3,3
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,20.880613,151.96765,1997.000000,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0,3,3
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,29.427878,157.00000,1920.000000,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0,4,4
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,19.026298,112.00000,1920.000000,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0,4,4

In [33]:
# Z score
x=np.array(df["Distance"])
m=np.mean(x)
s=np.std(x)

z_score = (x-m)/s

print("Original data:", x)
print("Z-scores:", z_score)
# df.plot(kind='hist',y=x)

Original data: [2.5 2.5 2.5 ... 6.8 6.8 6.3]
Z-scores: [-1.30148498 -1.30148498 -1.30148498 ... -0.56876052 -0.56876052
 -0.65396104]

In [35]:
# Define a threshold for outliers (e.g., z-score > 3 or < -3)
threshold = 3

# Find the indices of outliers
outlier_indices = np.where(np.abs(z_score) > threshold)[0]

# Remove outliers
data_array_without_outliers = np.delete(x, outlier_indices)

print("Original data:", len(x))
print("Data without outliers:", len(data_array_without_outliers))

Original data: 13580
Data without outliers: 13334